animals = [
    {
        "name": "Elephant",
        "category": "Mammal",
        "color": "Grey",
        "legs": 4,
        "diet": "Herbivore",
        "habitat": "Savanna",
        "can_fly": False,
        "can_swim": True,
        "lays_eggs": False,
        "lifespan": "60-70 years",
        "continent": "Africa/Asia",
        "size": "Large"
    },
    {
        "name": "Lion",
        "category": "Mammal",
        "color": "Golden",
        "legs": 4,
        "diet": "Carnivore",
        "habitat": "Savanna",
        "can_fly": False,
        "can_swim": False,
        "lays_eggs": False,
        "lifespan": "10-14 years",
        "continent": "Africa",
        "size": "Large"
    },
    {
        "name": "Tiger",
        "category": "Mammal",
        "color": "Orange with black stripes",
        "legs": 4,
        "diet": "Carnivore",
        "habitat": "Forest",
        "can_fly": False,
        "can_swim": True,
        "lays_eggs": False,
        "lifespan": "10-15 years",
        "continent": "Asia",
        "size": "Large"
    },
    {
        "name": "Penguin",
        "category": "Bird",
        "color": "Black and White",
        "legs": 2,
        "diet": "Carnivore",
        "habitat": "Cold regions",
        "can_fly": False,
        "can_swim": True,
        "lays_eggs": True,
        "lifespan": "15-20 years",
        "continent": "Antarctica",
        "size": "Medium"
    },
    {
        "name": "Eagle",
        "category": "Bird",
        "color": "Brown",
        "legs": 2,
        "diet": "Carnivore",
        "habitat": "Mountains",
        "can_fly": True,
        "can_swim": False,
        "lays_eggs": True,
        "lifespan": "20-30 years",
        "continent": "Worldwide",
        "size": "Medium"
    },
    {
        "name": "Dolphin",
        "category": "Mammal",
        "color": "Grey",
        "legs": 0,
        "diet": "Carnivore",
        "habitat": "Ocean",
        "can_fly": False,
        "can_swim": True,
        "lays_eggs": False,
        "lifespan": "40-60 years",
        "continent": "Oceans",
        "size": "Medium"
    },
    {
        "name": "Shark",
        "category": "Fish",
        "color": "Grey",
        "legs": 0,
        "diet": "Carnivore",
        "habitat": "Ocean",
        "can_fly": False,
        "can_swim": True,
        "lays_eggs": False,
        "lifespan": "20-30 years",
        "continent": "Oceans",
        "size": "Large"
    },
    {
        "name": "Camel",
        "category": "Mammal",
        "color": "Brown",
        "legs": 4,
        "diet": "Herbivore",
        "habitat": "Desert",
        "can_fly": False,
        "can_swim": False,
        "lays_eggs": False,
        "lifespan": "40-50 years",
        "continent": "Africa/Asia",
        "size": "Large"
    },
    {
        "name": "Rabbit",
        "category": "Mammal",
        "color": "White/Grey/Brown",
        "legs": 4,
        "diet": "Herbivore",
        "habitat": "Grasslands",
        "can_fly": False,
        "can_swim": False,
        "lays_eggs": False,
        "lifespan": "8-12 years",
        "continent": "Worldwide",
        "size": "Small"
    },
    {
        "name": "Frog",
        "category": "Amphibian",
        "color": "Green",
        "legs": 4,
        "diet": "Carnivore",
        "habitat": "Wetlands",
        "can_fly": False,
        "can_swim": True,
        "lays_eggs": True,
        "lifespan": "5-10 years",
        "continent": "Worldwide",
        "size": "Small"
    }
]

